---
title: "Rockefeller Center Energy Analysis"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

A look at three years of electric and steam consumption at Rockefeller Center. 



```{r Data Setup, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

# Load packages 
my_packages <- c("tidyverse", "vroom" , "janitor" , "glue" , "tsibble" , "tidytext","lubridate", "fable", "tsibbledata", "ggplot2", "forecast", "tseries", "rio", "zoo", "readxl", "tsibbledata", "knitr", "kableExtra", "formattable", "scales")
invisible( lapply(my_packages, require, character.only = TRUE))

#Set up environment 
place <- "Home"  #Where are we working today. 
# place <- "work"

if (place == "Home"){setwd("C:/Users/paulr/Documents/R/RockCenterEnergyAnalysis")} else {setwd("C:/Users/prode/Documents/R/RockCenterEnergyAnalysis")}

if (!file.exists("data")) { dir.create("data")}

rm(place, my_packages ) #Clean up

options(dplyr.summarise.inform = FALSE)  # Suppress textin Knit printout. 



# Read in data

'ElecCF' <- 0.000288962  #2021 Carbon Values
'SteamCF' <- 0.00004493 #2021 Carbon Values
'IntensityLimit24' <- 0.00846 #2024 Limit
'IntensityLimit30' <- 0.00453 #2030 Limit

SteamData <- read_excel("data/Energy_Data_for_Net_Zero_Study.xlsx", sheet = "Sheet1", range = "B2:G11" , col_names = TRUE, na = "NA", col_types = NULL ) %>%  select(-5,-6)

ElectricData <- read_excel("data/Energy_Data_for_Net_Zero_Study.xlsx", sheet = "Sheet1", range = "B13:G23" , col_names = TRUE, na = "NA", col_types = NULL ) %>% select(-5,-6)

ElectricData %>% filter(Building == '1 Rock' | Building == '600 5th') %>% 
  select( -Building) %>% 
  summarise_each(funs(sum)) %>% 
  mutate(Building = "1 Rock and 600 5th") %>% 
  select(4,1,2,3) %>% rbind(ElectricData) %>% 
  filter(Building != '1 Rock' & Building != '600 5th') -> ElectricData

BuildingGSF <- read_excel("data/Energy_Data_for_Net_Zero_Study.xlsx", sheet = "Sheet1", range = "B28:C39" , col_names = TRUE, na = "NA", col_types = NULL ) %>% 
  filter(Building != '1 Rock' & Building != '600 5th')

UtilityData <- left_join(ElectricData, SteamData, by="Building") %>% left_join(BuildingGSF, by="Building")
UtilityData[is.na(UtilityData)] <- 0

#Campus EUI for each year 
UtilityData1 <- UtilityData 
apply(UtilityData1[2:4], 2, function(row) row * 3.4121 ) -> UtilityData1[2:4]
apply(UtilityData1[5:7], 2, function(row) row * 1194) -> UtilityData1[5:7]
UtilityData1 %>% select(`2019 kwh`, `2020 kwh`, `2021 kwh`, `2019 mlbs`, `2020 mlbs`, `2021 mlbs`, `Gross Floor Area`) %>%
summarise_each(funs(sum)) -> UtilityData1
    TotalFlArea <- UtilityData1$`Gross Floor Area`
    UtilityData1 %>% 
      select(-`Gross Floor Area`) %>% 
  gather(key = "Item", value = "Value") -> UtilityData1
  cbind(UtilityData1, str_split_fixed(UtilityData1$Item, " ", n=2)) %>% 
  select(-"Item") -> UtilityData1 
  colnames(UtilityData1)  <-  c("Value", "Year", "Unit") 
  apply(UtilityData1[3], 1, function(x) {ifelse(x == "kwh", "Elec(kBTU)", "Steam(kBTU)")}) -> UtilityData1[3]

  ####  PLOTS   ####
  
  
# Make an EUI plot with kBTU vales for both  electric and steam  
UtilityData2 <- UtilityData1
apply(UtilityData2[1], 1, function(row) row / TotalFlArea ) -> UtilityData2[1]
UtilityData2 %>% 
  ggplot(aes(x = Year, y = Value, fill = Unit)) +
  geom_bar(stat = "identity", position = "stack") +
  labs( title = "Energy Use Density by fuel type for Campus",
        subtitle = "Units are kBTU's per year per Gross Squar Feet") +
  xlab("Year") +
  ylab("kBTU/SF") +
  scale_fill_manual(values = c("#CC0033", "#FFFFCC"))


#Make a Carbon table in the dataframe UtilityData1
UtilityData3 <- UtilityData1
  apply(UtilityData3[3], 1, function(x) {ifelse(x == "Elec(kBTU)", "Elect(tCO2e)", "Steam(tCO2e)")}) -> UtilityData3[3]
  UtilityData3 %>% 
  mutate(Carbon = ifelse(Unit == "Elec(kBTU)", Value * ElecCF / 3.4121, Value * SteamCF)) %>% 
  ggplot(aes(x = Year, y = Carbon, fill = Unit)) +
  geom_bar(stat = "identity", position = "stack") +
  labs( title = "Carbon by fuel type",
        subtitle = "Units are Carbon's per year") +
  labs(x = "Year", y = "tCO2e") +
  #guides(fill = FALSE) +
  geom_hline(aes(yintercept = TotalFlArea * IntensityLimit24), color = "blue", linetype = "dashed", size = 0.75) +
  geom_text(aes(x = 2, y = TotalFlArea * IntensityLimit24, label = "2024 Carbon Limit"), hjust = 1, vjust = 1.25 , color = "blue") +
  geom_hline(aes(yintercept = TotalFlArea * IntensityLimit30), linetype = "dashed", color = "blue", size = 0.5, alpha = 0.5) +
  geom_text(aes(x = 2, y = TotalFlArea * IntensityLimit30, label = "2030 Carbon Limit"), hjust = 0, vjust = -.2 , color = "blue", alpha = 0.1) +
  scale_fill_manual(values = c("#CC0033", "#FFFFCC"))


```
```{r  echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

#Plot Carbon Intensities versus LL97 Limits 
UtilityData1 <- UtilityData 
#apply(UtilityData1[2:4], 2, function(row) row * 3.4121 ) -> UtilityData1[2:4]
apply(UtilityData1[5:7], 2, function(row) row * 1194) -> UtilityData1[5:7]
UtilityData1[2:7]/UtilityData1$`Gross Floor Area` -> UtilityData1[2:7]


UtilityData1 %>% select(`Building`, `2019 kwh`, `2020 kwh`, `2021 kwh`, `2019 mlbs`, `2020 mlbs`, `2021 mlbs`) -> UtilityData1

UtilityData1 %>% 
  gather(key = "Item", value = "Value", -"Building") -> UtilityData1
  cbind(UtilityData1, str_split_fixed(UtilityData1$Item, " ", n=2)) %>% 
  select(-"Item") -> UtilityData1 
  colnames(UtilityData1)  <-  c("Building", "Value", "Year", "Unit") 
  UtilityData1 %>% 
    mutate("Carbon/SF" = ifelse(Unit == "Elec(kBTU)", Value * ElecCF, Value * SteamCF)) %>% 
    select(Building, Year, Unit, `Carbon/SF`) %>% 
    mutate("Carbon" = "tCO2e") -> UtilityData1


UtilityData1 %>%   
ggplot(aes(x = Year, y = `Carbon/SF`, fill = Building, group = Building)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs( title = "Carbon by Building",
        subtitle = "Units are tCO2e/GSF") +
  labs(x = "Building", y = "tCO2e/sf") +
  geom_hline(aes(yintercept = IntensityLimit24), color = "blue", linetype = "dashed", size = 0.75) +
  geom_text(aes(x = 2, y = IntensityLimit24, label = "2024 Carbon Limit"), hjust = 1, vjust = 1.25 , color = "blue") +
  geom_hline(aes(yintercept = IntensityLimit30), linetype = "dashed", color = "blue", size = 0.5, alpha = 0.5) +
  geom_text(aes(x = 2, y = IntensityLimit30, label = "2030 Carbon Limit"), hjust = 0, vjust = -.2 , color = "blue", alpha = 0.1) 
  

```




```{r  echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

#1 Electric kWh
ElectricData %>% select(Building, `2019 kwh`, `2020 kwh`, `2021 kwh`) %>% 
  gather(key = "Item", value = "Value", -Building) %>%
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")

#2 Electric kWh per GSF 
UtilityData1 <- UtilityData
apply(UtilityData1[2:7], 2, function(row) row / UtilityData1$`Gross Floor Area`) -> UtilityData1[2:7]


UtilityData1 %>% select(Building, `2019 kwh`, `2020 kwh`, `2021 kwh`) %>% 
  gather(key = "Item", value = "Value", -Building) %>% 
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")

#3 percent kWh reductions relative to 2019 
UtilityData1 <- UtilityData
apply(UtilityData1[2:7], 2, function(row) row / UtilityData1$`Gross Floor Area`) -> UtilityData1[2:7]
apply(UtilityData1[2:4], 2, function(row) row / UtilityData1$`2019 kwh`) -> UtilityData1[2:4]
UtilityData1 %>% select(Building, `2019 kwh`, `2020 kwh`, `2021 kwh`) %>% 
  gather(key = "Item", value = "Value", -Building) %>% 
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")
rm(UtilityData1)





# 4 Steam mlb 
SteamData %>% select(Building, `2019 mlbs`, `2020 mlbs`, `2021 mlbs`) %>% 
  gather(key = "Item", value = "Value", -Building) %>%
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")

#5 steam mlb per gsf 
UtilityData1 <- UtilityData
apply(UtilityData1[2:7], 2, function(row) row / UtilityData1$`Gross Floor Area`) -> UtilityData1[2:7]
UtilityData1 %>% select(Building, `2019 mlbs`, `2020 mlbs`, `2021 mlbs`) %>% 
  gather(key = "Item", value = "Value", -Building) %>% 
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")


#6 percent down from 2019
UtilityData1 <- UtilityData
apply(UtilityData1[2:7], 2, function(row) row / UtilityData1$`Gross Floor Area`) -> UtilityData1[2:7]
apply(UtilityData1[5:7], 2, function(row) row / UtilityData1$`2019 mlbs`) -> UtilityData1[5:7]
UtilityData1 %>% select(Building, `2019 mlbs`, `2020 mlbs`, `2021 mlbs`) %>% 
  gather(key = "Item", value = "Value", -Building) %>% 
  ggplot(aes(x = Building, y = Value, fill = Item, group = Item)) +
  geom_bar(stat = "identity", position = "dodge")



```


```{r  echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}


EPA_data <- read_excel("data/EPA_Annual_Energy_Use_By_Meter.xlsx", range = "A6:BB155" , col_names = FALSE, na = "NA", col_types = NULL )

EPA_data <- read_excel("data/EPA_Annual_Energy_Use_By_Meter.xlsx", skip = 4)


```
